version: 2.1

orbs:
  win: cicleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout
      - run: cd src
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore

